/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ClientAuthRouteImport } from './routes/client-auth'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClientRouteRouteImport } from './routes/_client/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ClientPortalRouteImport } from './routes/_client/portal'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDeadlinesRouteImport } from './routes/_authenticated/deadlines'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConnectZohoRouteImport } from './routes/_authenticated/connect-zoho'
import { Route as ClientPortalIndexRouteImport } from './routes/_client/portal.index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads.index'
import { Route as AuthenticatedEngagementsIndexRouteImport } from './routes/_authenticated/engagements.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicMedicalRecordsSweepRouteImport } from './routes/api/public/medical-records-sweep'
import { Route as ApiPublicDeadlineSweepRouteImport } from './routes/api/public/deadline-sweep'
import { Route as ClientPortalIntakeRouteImport } from './routes/_client/portal.intake'
import { Route as ClientPortalMatterIdRouteImport } from './routes/_client/portal.$matterId'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings.users'
import { Route as AuthenticatedSettingsTrustLedgerRouteImport } from './routes/_authenticated/settings.trust-ledger'
import { Route as AuthenticatedSettingsTrustExportRouteImport } from './routes/_authenticated/settings.trust-export'
import { Route as AuthenticatedSettingsStageRequirementsRouteImport } from './routes/_authenticated/settings.stage-requirements'
import { Route as AuthenticatedSettingsMessagingRouteImport } from './routes/_authenticated/settings.messaging'
import { Route as AuthenticatedSettingsDeadlineSweepRouteImport } from './routes/_authenticated/settings.deadline-sweep'
import { Route as AuthenticatedSettingsConnectionsRouteImport } from './routes/_authenticated/settings.connections'
import { Route as AuthenticatedSettingsChangelogRouteImport } from './routes/_authenticated/settings.changelog'
import { Route as AuthenticatedSettingsActivityRouteImport } from './routes/_authenticated/settings.activity'
import { Route as AuthenticatedPracticesSsdiRouteImport } from './routes/_authenticated/practices.ssdi'
import { Route as AuthenticatedPracticesPracticeRouteImport } from './routes/_authenticated/practices.$practice'
import { Route as AuthenticatedLeadsLeadIdRouteImport } from './routes/_authenticated/leads.$leadId'
import { Route as AuthenticatedEngagementsEngagementIdRouteImport } from './routes/_authenticated/engagements.$engagementId'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients.$clientId'
import { Route as AuthenticatedPracticesSsdiIndexRouteImport } from './routes/_authenticated/practices.ssdi.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiZohoConnectCallbackRouteImport } from './routes/api/zoho/connect/callback'
import { Route as ApiPublicWebhooksZohoSignRouteImport } from './routes/api/public/webhooks/zoho-sign'
import { Route as AuthenticatedPracticesSsdiIntakeRouteImport } from './routes/_authenticated/practices.ssdi.intake'
import { Route as AuthenticatedPracticesSsdiCasesIndexRouteImport } from './routes/_authenticated/practices.ssdi.cases.index'
import { Route as AuthenticatedPracticesSsdiReportsReferralsRouteImport } from './routes/_authenticated/practices.ssdi.reports.referrals'
import { Route as AuthenticatedPracticesSsdiReportsPipelineRouteImport } from './routes/_authenticated/practices.ssdi.reports.pipeline'
import { Route as AuthenticatedPracticesSsdiReportsOutcomesRouteImport } from './routes/_authenticated/practices.ssdi.reports.outcomes'
import { Route as AuthenticatedPracticesSsdiCasesCaseIdRouteImport } from './routes/_authenticated/practices.ssdi.cases.$caseId'
import { Route as AuthenticatedPracticesSsdiCasesCaseIdFeePetitionRouteImport } from './routes/_authenticated/practices.ssdi.cases.$caseId.fee-petition'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientAuthRoute = ClientAuthRouteImport.update({
  id: '/client-auth',
  path: '/client-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRouteRoute = ClientRouteRouteImport.update({
  id: '/_client',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientPortalRoute = ClientPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => ClientRouteRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeadlinesRoute = AuthenticatedDeadlinesRouteImport.update({
  id: '/deadlines',
  path: '/deadlines',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConnectZohoRoute =
  AuthenticatedConnectZohoRouteImport.update({
    id: '/connect-zoho',
    path: '/connect-zoho',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ClientPortalIndexRoute = ClientPortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientPortalRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEngagementsIndexRoute =
  AuthenticatedEngagementsIndexRouteImport.update({
    id: '/engagements/',
    path: '/engagements/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMedicalRecordsSweepRoute =
  ApiPublicMedicalRecordsSweepRouteImport.update({
    id: '/api/public/medical-records-sweep',
    path: '/api/public/medical-records-sweep',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDeadlineSweepRoute = ApiPublicDeadlineSweepRouteImport.update({
  id: '/api/public/deadline-sweep',
  path: '/api/public/deadline-sweep',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientPortalIntakeRoute = ClientPortalIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => ClientPortalRoute,
} as any)
const ClientPortalMatterIdRoute = ClientPortalMatterIdRouteImport.update({
  id: '/$matterId',
  path: '/$matterId',
  getParentRoute: () => ClientPortalRoute,
} as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTrustLedgerRoute =
  AuthenticatedSettingsTrustLedgerRouteImport.update({
    id: '/trust-ledger',
    path: '/trust-ledger',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTrustExportRoute =
  AuthenticatedSettingsTrustExportRouteImport.update({
    id: '/trust-export',
    path: '/trust-export',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsStageRequirementsRoute =
  AuthenticatedSettingsStageRequirementsRouteImport.update({
    id: '/stage-requirements',
    path: '/stage-requirements',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsMessagingRoute =
  AuthenticatedSettingsMessagingRouteImport.update({
    id: '/messaging',
    path: '/messaging',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsDeadlineSweepRoute =
  AuthenticatedSettingsDeadlineSweepRouteImport.update({
    id: '/deadline-sweep',
    path: '/deadline-sweep',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsConnectionsRoute =
  AuthenticatedSettingsConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsChangelogRoute =
  AuthenticatedSettingsChangelogRouteImport.update({
    id: '/changelog',
    path: '/changelog',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsActivityRoute =
  AuthenticatedSettingsActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedPracticesSsdiRoute =
  AuthenticatedPracticesSsdiRouteImport.update({
    id: '/practices/ssdi',
    path: '/practices/ssdi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticesPracticeRoute =
  AuthenticatedPracticesPracticeRouteImport.update({
    id: '/practices/$practice',
    path: '/practices/$practice',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadsLeadIdRoute =
  AuthenticatedLeadsLeadIdRouteImport.update({
    id: '/leads/$leadId',
    path: '/leads/$leadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEngagementsEngagementIdRoute =
  AuthenticatedEngagementsEngagementIdRouteImport.update({
    id: '/engagements/$engagementId',
    path: '/engagements/$engagementId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticesSsdiIndexRoute =
  AuthenticatedPracticesSsdiIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPracticesSsdiRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZohoConnectCallbackRoute = ApiZohoConnectCallbackRouteImport.update({
  id: '/api/zoho/connect/callback',
  path: '/api/zoho/connect/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksZohoSignRoute =
  ApiPublicWebhooksZohoSignRouteImport.update({
    id: '/api/public/webhooks/zoho-sign',
    path: '/api/public/webhooks/zoho-sign',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPracticesSsdiIntakeRoute =
  AuthenticatedPracticesSsdiIntakeRouteImport.update({
    id: '/intake',
    path: '/intake',
    getParentRoute: () => AuthenticatedPracticesSsdiRoute,
  } as any)
const AuthenticatedPracticesSsdiCasesIndexRoute =
  AuthenticatedPracticesSsdiCasesIndexRouteImport.update({
    id: '/cases/',
    path: '/cases/',
    getParentRoute: () => AuthenticatedPracticesSsdiRoute,
  } as any)
const AuthenticatedPracticesSsdiReportsReferralsRoute =
  AuthenticatedPracticesSsdiReportsReferralsRouteImport.update({
    id: '/reports/referrals',
    path: '/reports/referrals',
    getParentRoute: () => AuthenticatedPracticesSsdiRoute,
  } as any)
const AuthenticatedPracticesSsdiReportsPipelineRoute =
  AuthenticatedPracticesSsdiReportsPipelineRouteImport.update({
    id: '/reports/pipeline',
    path: '/reports/pipeline',
    getParentRoute: () => AuthenticatedPracticesSsdiRoute,
  } as any)
const AuthenticatedPracticesSsdiReportsOutcomesRoute =
  AuthenticatedPracticesSsdiReportsOutcomesRouteImport.update({
    id: '/reports/outcomes',
    path: '/reports/outcomes',
    getParentRoute: () => AuthenticatedPracticesSsdiRoute,
  } as any)
const AuthenticatedPracticesSsdiCasesCaseIdRoute =
  AuthenticatedPracticesSsdiCasesCaseIdRouteImport.update({
    id: '/cases/$caseId',
    path: '/cases/$caseId',
    getParentRoute: () => AuthenticatedPracticesSsdiRoute,
  } as any)
const AuthenticatedPracticesSsdiCasesCaseIdFeePetitionRoute =
  AuthenticatedPracticesSsdiCasesCaseIdFeePetitionRouteImport.update({
    id: '/fee-petition',
    path: '/fee-petition',
    getParentRoute: () => AuthenticatedPracticesSsdiCasesCaseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/client-auth': typeof ClientAuthRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/connect-zoho': typeof AuthenticatedConnectZohoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deadlines': typeof AuthenticatedDeadlinesRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/today': typeof AuthenticatedTodayRoute
  '/portal': typeof ClientPortalRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/engagements/$engagementId': typeof AuthenticatedEngagementsEngagementIdRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/practices/$practice': typeof AuthenticatedPracticesPracticeRoute
  '/practices/ssdi': typeof AuthenticatedPracticesSsdiRouteWithChildren
  '/settings/activity': typeof AuthenticatedSettingsActivityRoute
  '/settings/changelog': typeof AuthenticatedSettingsChangelogRoute
  '/settings/connections': typeof AuthenticatedSettingsConnectionsRoute
  '/settings/deadline-sweep': typeof AuthenticatedSettingsDeadlineSweepRoute
  '/settings/messaging': typeof AuthenticatedSettingsMessagingRoute
  '/settings/stage-requirements': typeof AuthenticatedSettingsStageRequirementsRoute
  '/settings/trust-export': typeof AuthenticatedSettingsTrustExportRoute
  '/settings/trust-ledger': typeof AuthenticatedSettingsTrustLedgerRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/portal/$matterId': typeof ClientPortalMatterIdRoute
  '/portal/intake': typeof ClientPortalIntakeRoute
  '/api/public/deadline-sweep': typeof ApiPublicDeadlineSweepRoute
  '/api/public/medical-records-sweep': typeof ApiPublicMedicalRecordsSweepRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/engagements/': typeof AuthenticatedEngagementsIndexRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/portal/': typeof ClientPortalIndexRoute
  '/practices/ssdi/intake': typeof AuthenticatedPracticesSsdiIntakeRoute
  '/api/public/webhooks/zoho-sign': typeof ApiPublicWebhooksZohoSignRoute
  '/api/zoho/connect/callback': typeof ApiZohoConnectCallbackRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/practices/ssdi/': typeof AuthenticatedPracticesSsdiIndexRoute
  '/practices/ssdi/cases/$caseId': typeof AuthenticatedPracticesSsdiCasesCaseIdRouteWithChildren
  '/practices/ssdi/reports/outcomes': typeof AuthenticatedPracticesSsdiReportsOutcomesRoute
  '/practices/ssdi/reports/pipeline': typeof AuthenticatedPracticesSsdiReportsPipelineRoute
  '/practices/ssdi/reports/referrals': typeof AuthenticatedPracticesSsdiReportsReferralsRoute
  '/practices/ssdi/cases/': typeof AuthenticatedPracticesSsdiCasesIndexRoute
  '/practices/ssdi/cases/$caseId/fee-petition': typeof AuthenticatedPracticesSsdiCasesCaseIdFeePetitionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/client-auth': typeof ClientAuthRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/connect-zoho': typeof AuthenticatedConnectZohoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deadlines': typeof AuthenticatedDeadlinesRoute
  '/today': typeof AuthenticatedTodayRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/engagements/$engagementId': typeof AuthenticatedEngagementsEngagementIdRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/practices/$practice': typeof AuthenticatedPracticesPracticeRoute
  '/settings/activity': typeof AuthenticatedSettingsActivityRoute
  '/settings/changelog': typeof AuthenticatedSettingsChangelogRoute
  '/settings/connections': typeof AuthenticatedSettingsConnectionsRoute
  '/settings/deadline-sweep': typeof AuthenticatedSettingsDeadlineSweepRoute
  '/settings/messaging': typeof AuthenticatedSettingsMessagingRoute
  '/settings/stage-requirements': typeof AuthenticatedSettingsStageRequirementsRoute
  '/settings/trust-export': typeof AuthenticatedSettingsTrustExportRoute
  '/settings/trust-ledger': typeof AuthenticatedSettingsTrustLedgerRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/portal/$matterId': typeof ClientPortalMatterIdRoute
  '/portal/intake': typeof ClientPortalIntakeRoute
  '/api/public/deadline-sweep': typeof ApiPublicDeadlineSweepRoute
  '/api/public/medical-records-sweep': typeof ApiPublicMedicalRecordsSweepRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/engagements': typeof AuthenticatedEngagementsIndexRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/portal': typeof ClientPortalIndexRoute
  '/practices/ssdi/intake': typeof AuthenticatedPracticesSsdiIntakeRoute
  '/api/public/webhooks/zoho-sign': typeof ApiPublicWebhooksZohoSignRoute
  '/api/zoho/connect/callback': typeof ApiZohoConnectCallbackRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/practices/ssdi': typeof AuthenticatedPracticesSsdiIndexRoute
  '/practices/ssdi/cases/$caseId': typeof AuthenticatedPracticesSsdiCasesCaseIdRouteWithChildren
  '/practices/ssdi/reports/outcomes': typeof AuthenticatedPracticesSsdiReportsOutcomesRoute
  '/practices/ssdi/reports/pipeline': typeof AuthenticatedPracticesSsdiReportsPipelineRoute
  '/practices/ssdi/reports/referrals': typeof AuthenticatedPracticesSsdiReportsReferralsRoute
  '/practices/ssdi/cases': typeof AuthenticatedPracticesSsdiCasesIndexRoute
  '/practices/ssdi/cases/$caseId/fee-petition': typeof AuthenticatedPracticesSsdiCasesCaseIdFeePetitionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_client': typeof ClientRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/client-auth': typeof ClientAuthRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/connect-zoho': typeof AuthenticatedConnectZohoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deadlines': typeof AuthenticatedDeadlinesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_client/portal': typeof ClientPortalRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/_authenticated/engagements/$engagementId': typeof AuthenticatedEngagementsEngagementIdRoute
  '/_authenticated/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/_authenticated/practices/$practice': typeof AuthenticatedPracticesPracticeRoute
  '/_authenticated/practices/ssdi': typeof AuthenticatedPracticesSsdiRouteWithChildren
  '/_authenticated/settings/activity': typeof AuthenticatedSettingsActivityRoute
  '/_authenticated/settings/changelog': typeof AuthenticatedSettingsChangelogRoute
  '/_authenticated/settings/connections': typeof AuthenticatedSettingsConnectionsRoute
  '/_authenticated/settings/deadline-sweep': typeof AuthenticatedSettingsDeadlineSweepRoute
  '/_authenticated/settings/messaging': typeof AuthenticatedSettingsMessagingRoute
  '/_authenticated/settings/stage-requirements': typeof AuthenticatedSettingsStageRequirementsRoute
  '/_authenticated/settings/trust-export': typeof AuthenticatedSettingsTrustExportRoute
  '/_authenticated/settings/trust-ledger': typeof AuthenticatedSettingsTrustLedgerRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_client/portal/$matterId': typeof ClientPortalMatterIdRoute
  '/_client/portal/intake': typeof ClientPortalIntakeRoute
  '/api/public/deadline-sweep': typeof ApiPublicDeadlineSweepRoute
  '/api/public/medical-records-sweep': typeof ApiPublicMedicalRecordsSweepRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/engagements/': typeof AuthenticatedEngagementsIndexRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_client/portal/': typeof ClientPortalIndexRoute
  '/_authenticated/practices/ssdi/intake': typeof AuthenticatedPracticesSsdiIntakeRoute
  '/api/public/webhooks/zoho-sign': typeof ApiPublicWebhooksZohoSignRoute
  '/api/zoho/connect/callback': typeof ApiZohoConnectCallbackRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/practices/ssdi/': typeof AuthenticatedPracticesSsdiIndexRoute
  '/_authenticated/practices/ssdi/cases/$caseId': typeof AuthenticatedPracticesSsdiCasesCaseIdRouteWithChildren
  '/_authenticated/practices/ssdi/reports/outcomes': typeof AuthenticatedPracticesSsdiReportsOutcomesRoute
  '/_authenticated/practices/ssdi/reports/pipeline': typeof AuthenticatedPracticesSsdiReportsPipelineRoute
  '/_authenticated/practices/ssdi/reports/referrals': typeof AuthenticatedPracticesSsdiReportsReferralsRoute
  '/_authenticated/practices/ssdi/cases/': typeof AuthenticatedPracticesSsdiCasesIndexRoute
  '/_authenticated/practices/ssdi/cases/$caseId/fee-petition': typeof AuthenticatedPracticesSsdiCasesCaseIdFeePetitionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/client-auth'
    | '/unsubscribe'
    | '/connect-zoho'
    | '/dashboard'
    | '/deadlines'
    | '/settings'
    | '/today'
    | '/portal'
    | '/email/unsubscribe'
    | '/clients/$clientId'
    | '/engagements/$engagementId'
    | '/leads/$leadId'
    | '/practices/$practice'
    | '/practices/ssdi'
    | '/settings/activity'
    | '/settings/changelog'
    | '/settings/connections'
    | '/settings/deadline-sweep'
    | '/settings/messaging'
    | '/settings/stage-requirements'
    | '/settings/trust-export'
    | '/settings/trust-ledger'
    | '/settings/users'
    | '/portal/$matterId'
    | '/portal/intake'
    | '/api/public/deadline-sweep'
    | '/api/public/medical-records-sweep'
    | '/lovable/email/suppression'
    | '/clients/'
    | '/engagements/'
    | '/leads/'
    | '/settings/'
    | '/portal/'
    | '/practices/ssdi/intake'
    | '/api/public/webhooks/zoho-sign'
    | '/api/zoho/connect/callback'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/practices/ssdi/'
    | '/practices/ssdi/cases/$caseId'
    | '/practices/ssdi/reports/outcomes'
    | '/practices/ssdi/reports/pipeline'
    | '/practices/ssdi/reports/referrals'
    | '/practices/ssdi/cases/'
    | '/practices/ssdi/cases/$caseId/fee-petition'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/client-auth'
    | '/unsubscribe'
    | '/connect-zoho'
    | '/dashboard'
    | '/deadlines'
    | '/today'
    | '/email/unsubscribe'
    | '/clients/$clientId'
    | '/engagements/$engagementId'
    | '/leads/$leadId'
    | '/practices/$practice'
    | '/settings/activity'
    | '/settings/changelog'
    | '/settings/connections'
    | '/settings/deadline-sweep'
    | '/settings/messaging'
    | '/settings/stage-requirements'
    | '/settings/trust-export'
    | '/settings/trust-ledger'
    | '/settings/users'
    | '/portal/$matterId'
    | '/portal/intake'
    | '/api/public/deadline-sweep'
    | '/api/public/medical-records-sweep'
    | '/lovable/email/suppression'
    | '/clients'
    | '/engagements'
    | '/leads'
    | '/settings'
    | '/portal'
    | '/practices/ssdi/intake'
    | '/api/public/webhooks/zoho-sign'
    | '/api/zoho/connect/callback'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/practices/ssdi'
    | '/practices/ssdi/cases/$caseId'
    | '/practices/ssdi/reports/outcomes'
    | '/practices/ssdi/reports/pipeline'
    | '/practices/ssdi/reports/referrals'
    | '/practices/ssdi/cases'
    | '/practices/ssdi/cases/$caseId/fee-petition'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_client'
    | '/auth'
    | '/client-auth'
    | '/unsubscribe'
    | '/_authenticated/connect-zoho'
    | '/_authenticated/dashboard'
    | '/_authenticated/deadlines'
    | '/_authenticated/settings'
    | '/_authenticated/today'
    | '/_client/portal'
    | '/email/unsubscribe'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/engagements/$engagementId'
    | '/_authenticated/leads/$leadId'
    | '/_authenticated/practices/$practice'
    | '/_authenticated/practices/ssdi'
    | '/_authenticated/settings/activity'
    | '/_authenticated/settings/changelog'
    | '/_authenticated/settings/connections'
    | '/_authenticated/settings/deadline-sweep'
    | '/_authenticated/settings/messaging'
    | '/_authenticated/settings/stage-requirements'
    | '/_authenticated/settings/trust-export'
    | '/_authenticated/settings/trust-ledger'
    | '/_authenticated/settings/users'
    | '/_client/portal/$matterId'
    | '/_client/portal/intake'
    | '/api/public/deadline-sweep'
    | '/api/public/medical-records-sweep'
    | '/lovable/email/suppression'
    | '/_authenticated/clients/'
    | '/_authenticated/engagements/'
    | '/_authenticated/leads/'
    | '/_authenticated/settings/'
    | '/_client/portal/'
    | '/_authenticated/practices/ssdi/intake'
    | '/api/public/webhooks/zoho-sign'
    | '/api/zoho/connect/callback'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/practices/ssdi/'
    | '/_authenticated/practices/ssdi/cases/$caseId'
    | '/_authenticated/practices/ssdi/reports/outcomes'
    | '/_authenticated/practices/ssdi/reports/pipeline'
    | '/_authenticated/practices/ssdi/reports/referrals'
    | '/_authenticated/practices/ssdi/cases/'
    | '/_authenticated/practices/ssdi/cases/$caseId/fee-petition'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClientRouteRoute: typeof ClientRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClientAuthRoute: typeof ClientAuthRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicDeadlineSweepRoute: typeof ApiPublicDeadlineSweepRoute
  ApiPublicMedicalRecordsSweepRoute: typeof ApiPublicMedicalRecordsSweepRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicWebhooksZohoSignRoute: typeof ApiPublicWebhooksZohoSignRoute
  ApiZohoConnectCallbackRoute: typeof ApiZohoConnectCallbackRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-auth': {
      id: '/client-auth'
      path: '/client-auth'
      fullPath: '/client-auth'
      preLoaderRoute: typeof ClientAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client': {
      id: '/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ClientRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client/portal': {
      id: '/_client/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof ClientPortalRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deadlines': {
      id: '/_authenticated/deadlines'
      path: '/deadlines'
      fullPath: '/deadlines'
      preLoaderRoute: typeof AuthenticatedDeadlinesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connect-zoho': {
      id: '/_authenticated/connect-zoho'
      path: '/connect-zoho'
      fullPath: '/connect-zoho'
      preLoaderRoute: typeof AuthenticatedConnectZohoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_client/portal/': {
      id: '/_client/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof ClientPortalIndexRouteImport
      parentRoute: typeof ClientPortalRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engagements/': {
      id: '/_authenticated/engagements/'
      path: '/engagements'
      fullPath: '/engagements/'
      preLoaderRoute: typeof AuthenticatedEngagementsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/medical-records-sweep': {
      id: '/api/public/medical-records-sweep'
      path: '/api/public/medical-records-sweep'
      fullPath: '/api/public/medical-records-sweep'
      preLoaderRoute: typeof ApiPublicMedicalRecordsSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/deadline-sweep': {
      id: '/api/public/deadline-sweep'
      path: '/api/public/deadline-sweep'
      fullPath: '/api/public/deadline-sweep'
      preLoaderRoute: typeof ApiPublicDeadlineSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client/portal/intake': {
      id: '/_client/portal/intake'
      path: '/intake'
      fullPath: '/portal/intake'
      preLoaderRoute: typeof ClientPortalIntakeRouteImport
      parentRoute: typeof ClientPortalRoute
    }
    '/_client/portal/$matterId': {
      id: '/_client/portal/$matterId'
      path: '/$matterId'
      fullPath: '/portal/$matterId'
      preLoaderRoute: typeof ClientPortalMatterIdRouteImport
      parentRoute: typeof ClientPortalRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/trust-ledger': {
      id: '/_authenticated/settings/trust-ledger'
      path: '/trust-ledger'
      fullPath: '/settings/trust-ledger'
      preLoaderRoute: typeof AuthenticatedSettingsTrustLedgerRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/trust-export': {
      id: '/_authenticated/settings/trust-export'
      path: '/trust-export'
      fullPath: '/settings/trust-export'
      preLoaderRoute: typeof AuthenticatedSettingsTrustExportRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/stage-requirements': {
      id: '/_authenticated/settings/stage-requirements'
      path: '/stage-requirements'
      fullPath: '/settings/stage-requirements'
      preLoaderRoute: typeof AuthenticatedSettingsStageRequirementsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/messaging': {
      id: '/_authenticated/settings/messaging'
      path: '/messaging'
      fullPath: '/settings/messaging'
      preLoaderRoute: typeof AuthenticatedSettingsMessagingRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/deadline-sweep': {
      id: '/_authenticated/settings/deadline-sweep'
      path: '/deadline-sweep'
      fullPath: '/settings/deadline-sweep'
      preLoaderRoute: typeof AuthenticatedSettingsDeadlineSweepRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/connections': {
      id: '/_authenticated/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof AuthenticatedSettingsConnectionsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/changelog': {
      id: '/_authenticated/settings/changelog'
      path: '/changelog'
      fullPath: '/settings/changelog'
      preLoaderRoute: typeof AuthenticatedSettingsChangelogRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/activity': {
      id: '/_authenticated/settings/activity'
      path: '/activity'
      fullPath: '/settings/activity'
      preLoaderRoute: typeof AuthenticatedSettingsActivityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/practices/ssdi': {
      id: '/_authenticated/practices/ssdi'
      path: '/practices/ssdi'
      fullPath: '/practices/ssdi'
      preLoaderRoute: typeof AuthenticatedPracticesSsdiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practices/$practice': {
      id: '/_authenticated/practices/$practice'
      path: '/practices/$practice'
      fullPath: '/practices/$practice'
      preLoaderRoute: typeof AuthenticatedPracticesPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/$leadId': {
      id: '/_authenticated/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AuthenticatedLeadsLeadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engagements/$engagementId': {
      id: '/_authenticated/engagements/$engagementId'
      path: '/engagements/$engagementId'
      fullPath: '/engagements/$engagementId'
      preLoaderRoute: typeof AuthenticatedEngagementsEngagementIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practices/ssdi/': {
      id: '/_authenticated/practices/ssdi/'
      path: '/'
      fullPath: '/practices/ssdi/'
      preLoaderRoute: typeof AuthenticatedPracticesSsdiIndexRouteImport
      parentRoute: typeof AuthenticatedPracticesSsdiRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zoho/connect/callback': {
      id: '/api/zoho/connect/callback'
      path: '/api/zoho/connect/callback'
      fullPath: '/api/zoho/connect/callback'
      preLoaderRoute: typeof ApiZohoConnectCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/zoho-sign': {
      id: '/api/public/webhooks/zoho-sign'
      path: '/api/public/webhooks/zoho-sign'
      fullPath: '/api/public/webhooks/zoho-sign'
      preLoaderRoute: typeof ApiPublicWebhooksZohoSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/practices/ssdi/intake': {
      id: '/_authenticated/practices/ssdi/intake'
      path: '/intake'
      fullPath: '/practices/ssdi/intake'
      preLoaderRoute: typeof AuthenticatedPracticesSsdiIntakeRouteImport
      parentRoute: typeof AuthenticatedPracticesSsdiRoute
    }
    '/_authenticated/practices/ssdi/cases/': {
      id: '/_authenticated/practices/ssdi/cases/'
      path: '/cases'
      fullPath: '/practices/ssdi/cases/'
      preLoaderRoute: typeof AuthenticatedPracticesSsdiCasesIndexRouteImport
      parentRoute: typeof AuthenticatedPracticesSsdiRoute
    }
    '/_authenticated/practices/ssdi/reports/referrals': {
      id: '/_authenticated/practices/ssdi/reports/referrals'
      path: '/reports/referrals'
      fullPath: '/practices/ssdi/reports/referrals'
      preLoaderRoute: typeof AuthenticatedPracticesSsdiReportsReferralsRouteImport
      parentRoute: typeof AuthenticatedPracticesSsdiRoute
    }
    '/_authenticated/practices/ssdi/reports/pipeline': {
      id: '/_authenticated/practices/ssdi/reports/pipeline'
      path: '/reports/pipeline'
      fullPath: '/practices/ssdi/reports/pipeline'
      preLoaderRoute: typeof AuthenticatedPracticesSsdiReportsPipelineRouteImport
      parentRoute: typeof AuthenticatedPracticesSsdiRoute
    }
    '/_authenticated/practices/ssdi/reports/outcomes': {
      id: '/_authenticated/practices/ssdi/reports/outcomes'
      path: '/reports/outcomes'
      fullPath: '/practices/ssdi/reports/outcomes'
      preLoaderRoute: typeof AuthenticatedPracticesSsdiReportsOutcomesRouteImport
      parentRoute: typeof AuthenticatedPracticesSsdiRoute
    }
    '/_authenticated/practices/ssdi/cases/$caseId': {
      id: '/_authenticated/practices/ssdi/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/practices/ssdi/cases/$caseId'
      preLoaderRoute: typeof AuthenticatedPracticesSsdiCasesCaseIdRouteImport
      parentRoute: typeof AuthenticatedPracticesSsdiRoute
    }
    '/_authenticated/practices/ssdi/cases/$caseId/fee-petition': {
      id: '/_authenticated/practices/ssdi/cases/$caseId/fee-petition'
      path: '/fee-petition'
      fullPath: '/practices/ssdi/cases/$caseId/fee-petition'
      preLoaderRoute: typeof AuthenticatedPracticesSsdiCasesCaseIdFeePetitionRouteImport
      parentRoute: typeof AuthenticatedPracticesSsdiCasesCaseIdRoute
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsActivityRoute: typeof AuthenticatedSettingsActivityRoute
  AuthenticatedSettingsChangelogRoute: typeof AuthenticatedSettingsChangelogRoute
  AuthenticatedSettingsConnectionsRoute: typeof AuthenticatedSettingsConnectionsRoute
  AuthenticatedSettingsDeadlineSweepRoute: typeof AuthenticatedSettingsDeadlineSweepRoute
  AuthenticatedSettingsMessagingRoute: typeof AuthenticatedSettingsMessagingRoute
  AuthenticatedSettingsStageRequirementsRoute: typeof AuthenticatedSettingsStageRequirementsRoute
  AuthenticatedSettingsTrustExportRoute: typeof AuthenticatedSettingsTrustExportRoute
  AuthenticatedSettingsTrustLedgerRoute: typeof AuthenticatedSettingsTrustLedgerRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsActivityRoute: AuthenticatedSettingsActivityRoute,
  AuthenticatedSettingsChangelogRoute: AuthenticatedSettingsChangelogRoute,
  AuthenticatedSettingsConnectionsRoute: AuthenticatedSettingsConnectionsRoute,
  AuthenticatedSettingsDeadlineSweepRoute:
    AuthenticatedSettingsDeadlineSweepRoute,
  AuthenticatedSettingsMessagingRoute: AuthenticatedSettingsMessagingRoute,
  AuthenticatedSettingsStageRequirementsRoute:
    AuthenticatedSettingsStageRequirementsRoute,
  AuthenticatedSettingsTrustExportRoute: AuthenticatedSettingsTrustExportRoute,
  AuthenticatedSettingsTrustLedgerRoute: AuthenticatedSettingsTrustLedgerRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedPracticesSsdiCasesCaseIdRouteChildren {
  AuthenticatedPracticesSsdiCasesCaseIdFeePetitionRoute: typeof AuthenticatedPracticesSsdiCasesCaseIdFeePetitionRoute
}

const AuthenticatedPracticesSsdiCasesCaseIdRouteChildren: AuthenticatedPracticesSsdiCasesCaseIdRouteChildren =
  {
    AuthenticatedPracticesSsdiCasesCaseIdFeePetitionRoute:
      AuthenticatedPracticesSsdiCasesCaseIdFeePetitionRoute,
  }

const AuthenticatedPracticesSsdiCasesCaseIdRouteWithChildren =
  AuthenticatedPracticesSsdiCasesCaseIdRoute._addFileChildren(
    AuthenticatedPracticesSsdiCasesCaseIdRouteChildren,
  )

interface AuthenticatedPracticesSsdiRouteChildren {
  AuthenticatedPracticesSsdiIntakeRoute: typeof AuthenticatedPracticesSsdiIntakeRoute
  AuthenticatedPracticesSsdiIndexRoute: typeof AuthenticatedPracticesSsdiIndexRoute
  AuthenticatedPracticesSsdiCasesCaseIdRoute: typeof AuthenticatedPracticesSsdiCasesCaseIdRouteWithChildren
  AuthenticatedPracticesSsdiReportsOutcomesRoute: typeof AuthenticatedPracticesSsdiReportsOutcomesRoute
  AuthenticatedPracticesSsdiReportsPipelineRoute: typeof AuthenticatedPracticesSsdiReportsPipelineRoute
  AuthenticatedPracticesSsdiReportsReferralsRoute: typeof AuthenticatedPracticesSsdiReportsReferralsRoute
  AuthenticatedPracticesSsdiCasesIndexRoute: typeof AuthenticatedPracticesSsdiCasesIndexRoute
}

const AuthenticatedPracticesSsdiRouteChildren: AuthenticatedPracticesSsdiRouteChildren =
  {
    AuthenticatedPracticesSsdiIntakeRoute:
      AuthenticatedPracticesSsdiIntakeRoute,
    AuthenticatedPracticesSsdiIndexRoute: AuthenticatedPracticesSsdiIndexRoute,
    AuthenticatedPracticesSsdiCasesCaseIdRoute:
      AuthenticatedPracticesSsdiCasesCaseIdRouteWithChildren,
    AuthenticatedPracticesSsdiReportsOutcomesRoute:
      AuthenticatedPracticesSsdiReportsOutcomesRoute,
    AuthenticatedPracticesSsdiReportsPipelineRoute:
      AuthenticatedPracticesSsdiReportsPipelineRoute,
    AuthenticatedPracticesSsdiReportsReferralsRoute:
      AuthenticatedPracticesSsdiReportsReferralsRoute,
    AuthenticatedPracticesSsdiCasesIndexRoute:
      AuthenticatedPracticesSsdiCasesIndexRoute,
  }

const AuthenticatedPracticesSsdiRouteWithChildren =
  AuthenticatedPracticesSsdiRoute._addFileChildren(
    AuthenticatedPracticesSsdiRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConnectZohoRoute: typeof AuthenticatedConnectZohoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeadlinesRoute: typeof AuthenticatedDeadlinesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRoute
  AuthenticatedEngagementsEngagementIdRoute: typeof AuthenticatedEngagementsEngagementIdRoute
  AuthenticatedLeadsLeadIdRoute: typeof AuthenticatedLeadsLeadIdRoute
  AuthenticatedPracticesPracticeRoute: typeof AuthenticatedPracticesPracticeRoute
  AuthenticatedPracticesSsdiRoute: typeof AuthenticatedPracticesSsdiRouteWithChildren
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedEngagementsIndexRoute: typeof AuthenticatedEngagementsIndexRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConnectZohoRoute: AuthenticatedConnectZohoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeadlinesRoute: AuthenticatedDeadlinesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedClientsClientIdRoute: AuthenticatedClientsClientIdRoute,
  AuthenticatedEngagementsEngagementIdRoute:
    AuthenticatedEngagementsEngagementIdRoute,
  AuthenticatedLeadsLeadIdRoute: AuthenticatedLeadsLeadIdRoute,
  AuthenticatedPracticesPracticeRoute: AuthenticatedPracticesPracticeRoute,
  AuthenticatedPracticesSsdiRoute: AuthenticatedPracticesSsdiRouteWithChildren,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedEngagementsIndexRoute: AuthenticatedEngagementsIndexRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClientPortalRouteChildren {
  ClientPortalMatterIdRoute: typeof ClientPortalMatterIdRoute
  ClientPortalIntakeRoute: typeof ClientPortalIntakeRoute
  ClientPortalIndexRoute: typeof ClientPortalIndexRoute
}

const ClientPortalRouteChildren: ClientPortalRouteChildren = {
  ClientPortalMatterIdRoute: ClientPortalMatterIdRoute,
  ClientPortalIntakeRoute: ClientPortalIntakeRoute,
  ClientPortalIndexRoute: ClientPortalIndexRoute,
}

const ClientPortalRouteWithChildren = ClientPortalRoute._addFileChildren(
  ClientPortalRouteChildren,
)

interface ClientRouteRouteChildren {
  ClientPortalRoute: typeof ClientPortalRouteWithChildren
}

const ClientRouteRouteChildren: ClientRouteRouteChildren = {
  ClientPortalRoute: ClientPortalRouteWithChildren,
}

const ClientRouteRouteWithChildren = ClientRouteRoute._addFileChildren(
  ClientRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClientRouteRoute: ClientRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ClientAuthRoute: ClientAuthRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicDeadlineSweepRoute: ApiPublicDeadlineSweepRoute,
  ApiPublicMedicalRecordsSweepRoute: ApiPublicMedicalRecordsSweepRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicWebhooksZohoSignRoute: ApiPublicWebhooksZohoSignRoute,
  ApiZohoConnectCallbackRoute: ApiZohoConnectCallbackRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
