/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDeadlinesRouteImport } from './routes/_authenticated/deadlines'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConnectZohoRouteImport } from './routes/_authenticated/connect-zoho'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads.index'
import { Route as AuthenticatedEngagementsIndexRouteImport } from './routes/_authenticated/engagements.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as ApiPublicDeadlineSweepRouteImport } from './routes/api/public/deadline-sweep'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings.users'
import { Route as AuthenticatedSettingsTrustExportRouteImport } from './routes/_authenticated/settings.trust-export'
import { Route as AuthenticatedSettingsStageRequirementsRouteImport } from './routes/_authenticated/settings.stage-requirements'
import { Route as AuthenticatedSettingsDeadlineSweepRouteImport } from './routes/_authenticated/settings.deadline-sweep'
import { Route as AuthenticatedSettingsConnectionsRouteImport } from './routes/_authenticated/settings.connections'
import { Route as AuthenticatedSettingsChangelogRouteImport } from './routes/_authenticated/settings.changelog'
import { Route as AuthenticatedPracticesSsdiRouteImport } from './routes/_authenticated/practices.ssdi'
import { Route as AuthenticatedPracticesPracticeRouteImport } from './routes/_authenticated/practices.$practice'
import { Route as AuthenticatedLeadsLeadIdRouteImport } from './routes/_authenticated/leads.$leadId'
import { Route as AuthenticatedEngagementsEngagementIdRouteImport } from './routes/_authenticated/engagements.$engagementId'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients.$clientId'
import { Route as AuthenticatedPracticesSsdiIndexRouteImport } from './routes/_authenticated/practices.ssdi.index'
import { Route as ApiZohoConnectCallbackRouteImport } from './routes/api/zoho/connect/callback'
import { Route as ApiPublicWebhooksZohoSignRouteImport } from './routes/api/public/webhooks/zoho-sign'
import { Route as AuthenticatedPracticesSsdiIntakeRouteImport } from './routes/_authenticated/practices.ssdi.intake'
import { Route as AuthenticatedPracticesSsdiCasesIndexRouteImport } from './routes/_authenticated/practices.ssdi.cases.index'
import { Route as AuthenticatedPracticesSsdiReportsReferralsRouteImport } from './routes/_authenticated/practices.ssdi.reports.referrals'
import { Route as AuthenticatedPracticesSsdiReportsPipelineRouteImport } from './routes/_authenticated/practices.ssdi.reports.pipeline'
import { Route as AuthenticatedPracticesSsdiReportsOutcomesRouteImport } from './routes/_authenticated/practices.ssdi.reports.outcomes'
import { Route as AuthenticatedPracticesSsdiCasesCaseIdRouteImport } from './routes/_authenticated/practices.ssdi.cases.$caseId'
import { Route as AuthenticatedPracticesSsdiCasesCaseIdFeePetitionRouteImport } from './routes/_authenticated/practices.ssdi.cases.$caseId.fee-petition'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeadlinesRoute = AuthenticatedDeadlinesRouteImport.update({
  id: '/deadlines',
  path: '/deadlines',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConnectZohoRoute =
  AuthenticatedConnectZohoRouteImport.update({
    id: '/connect-zoho',
    path: '/connect-zoho',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEngagementsIndexRoute =
  AuthenticatedEngagementsIndexRouteImport.update({
    id: '/engagements/',
    path: '/engagements/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicDeadlineSweepRoute = ApiPublicDeadlineSweepRouteImport.update({
  id: '/api/public/deadline-sweep',
  path: '/api/public/deadline-sweep',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTrustExportRoute =
  AuthenticatedSettingsTrustExportRouteImport.update({
    id: '/trust-export',
    path: '/trust-export',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsStageRequirementsRoute =
  AuthenticatedSettingsStageRequirementsRouteImport.update({
    id: '/stage-requirements',
    path: '/stage-requirements',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsDeadlineSweepRoute =
  AuthenticatedSettingsDeadlineSweepRouteImport.update({
    id: '/deadline-sweep',
    path: '/deadline-sweep',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsConnectionsRoute =
  AuthenticatedSettingsConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsChangelogRoute =
  AuthenticatedSettingsChangelogRouteImport.update({
    id: '/changelog',
    path: '/changelog',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedPracticesSsdiRoute =
  AuthenticatedPracticesSsdiRouteImport.update({
    id: '/practices/ssdi',
    path: '/practices/ssdi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticesPracticeRoute =
  AuthenticatedPracticesPracticeRouteImport.update({
    id: '/practices/$practice',
    path: '/practices/$practice',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadsLeadIdRoute =
  AuthenticatedLeadsLeadIdRouteImport.update({
    id: '/leads/$leadId',
    path: '/leads/$leadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEngagementsEngagementIdRoute =
  AuthenticatedEngagementsEngagementIdRouteImport.update({
    id: '/engagements/$engagementId',
    path: '/engagements/$engagementId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticesSsdiIndexRoute =
  AuthenticatedPracticesSsdiIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPracticesSsdiRoute,
  } as any)
const ApiZohoConnectCallbackRoute = ApiZohoConnectCallbackRouteImport.update({
  id: '/api/zoho/connect/callback',
  path: '/api/zoho/connect/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksZohoSignRoute =
  ApiPublicWebhooksZohoSignRouteImport.update({
    id: '/api/public/webhooks/zoho-sign',
    path: '/api/public/webhooks/zoho-sign',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPracticesSsdiIntakeRoute =
  AuthenticatedPracticesSsdiIntakeRouteImport.update({
    id: '/intake',
    path: '/intake',
    getParentRoute: () => AuthenticatedPracticesSsdiRoute,
  } as any)
const AuthenticatedPracticesSsdiCasesIndexRoute =
  AuthenticatedPracticesSsdiCasesIndexRouteImport.update({
    id: '/cases/',
    path: '/cases/',
    getParentRoute: () => AuthenticatedPracticesSsdiRoute,
  } as any)
const AuthenticatedPracticesSsdiReportsReferralsRoute =
  AuthenticatedPracticesSsdiReportsReferralsRouteImport.update({
    id: '/reports/referrals',
    path: '/reports/referrals',
    getParentRoute: () => AuthenticatedPracticesSsdiRoute,
  } as any)
const AuthenticatedPracticesSsdiReportsPipelineRoute =
  AuthenticatedPracticesSsdiReportsPipelineRouteImport.update({
    id: '/reports/pipeline',
    path: '/reports/pipeline',
    getParentRoute: () => AuthenticatedPracticesSsdiRoute,
  } as any)
const AuthenticatedPracticesSsdiReportsOutcomesRoute =
  AuthenticatedPracticesSsdiReportsOutcomesRouteImport.update({
    id: '/reports/outcomes',
    path: '/reports/outcomes',
    getParentRoute: () => AuthenticatedPracticesSsdiRoute,
  } as any)
const AuthenticatedPracticesSsdiCasesCaseIdRoute =
  AuthenticatedPracticesSsdiCasesCaseIdRouteImport.update({
    id: '/cases/$caseId',
    path: '/cases/$caseId',
    getParentRoute: () => AuthenticatedPracticesSsdiRoute,
  } as any)
const AuthenticatedPracticesSsdiCasesCaseIdFeePetitionRoute =
  AuthenticatedPracticesSsdiCasesCaseIdFeePetitionRouteImport.update({
    id: '/fee-petition',
    path: '/fee-petition',
    getParentRoute: () => AuthenticatedPracticesSsdiCasesCaseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connect-zoho': typeof AuthenticatedConnectZohoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deadlines': typeof AuthenticatedDeadlinesRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/engagements/$engagementId': typeof AuthenticatedEngagementsEngagementIdRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/practices/$practice': typeof AuthenticatedPracticesPracticeRoute
  '/practices/ssdi': typeof AuthenticatedPracticesSsdiRouteWithChildren
  '/settings/changelog': typeof AuthenticatedSettingsChangelogRoute
  '/settings/connections': typeof AuthenticatedSettingsConnectionsRoute
  '/settings/deadline-sweep': typeof AuthenticatedSettingsDeadlineSweepRoute
  '/settings/stage-requirements': typeof AuthenticatedSettingsStageRequirementsRoute
  '/settings/trust-export': typeof AuthenticatedSettingsTrustExportRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/api/public/deadline-sweep': typeof ApiPublicDeadlineSweepRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/engagements/': typeof AuthenticatedEngagementsIndexRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/practices/ssdi/intake': typeof AuthenticatedPracticesSsdiIntakeRoute
  '/api/public/webhooks/zoho-sign': typeof ApiPublicWebhooksZohoSignRoute
  '/api/zoho/connect/callback': typeof ApiZohoConnectCallbackRoute
  '/practices/ssdi/': typeof AuthenticatedPracticesSsdiIndexRoute
  '/practices/ssdi/cases/$caseId': typeof AuthenticatedPracticesSsdiCasesCaseIdRouteWithChildren
  '/practices/ssdi/reports/outcomes': typeof AuthenticatedPracticesSsdiReportsOutcomesRoute
  '/practices/ssdi/reports/pipeline': typeof AuthenticatedPracticesSsdiReportsPipelineRoute
  '/practices/ssdi/reports/referrals': typeof AuthenticatedPracticesSsdiReportsReferralsRoute
  '/practices/ssdi/cases/': typeof AuthenticatedPracticesSsdiCasesIndexRoute
  '/practices/ssdi/cases/$caseId/fee-petition': typeof AuthenticatedPracticesSsdiCasesCaseIdFeePetitionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connect-zoho': typeof AuthenticatedConnectZohoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deadlines': typeof AuthenticatedDeadlinesRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/engagements/$engagementId': typeof AuthenticatedEngagementsEngagementIdRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/practices/$practice': typeof AuthenticatedPracticesPracticeRoute
  '/settings/changelog': typeof AuthenticatedSettingsChangelogRoute
  '/settings/connections': typeof AuthenticatedSettingsConnectionsRoute
  '/settings/deadline-sweep': typeof AuthenticatedSettingsDeadlineSweepRoute
  '/settings/stage-requirements': typeof AuthenticatedSettingsStageRequirementsRoute
  '/settings/trust-export': typeof AuthenticatedSettingsTrustExportRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/api/public/deadline-sweep': typeof ApiPublicDeadlineSweepRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/engagements': typeof AuthenticatedEngagementsIndexRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/practices/ssdi/intake': typeof AuthenticatedPracticesSsdiIntakeRoute
  '/api/public/webhooks/zoho-sign': typeof ApiPublicWebhooksZohoSignRoute
  '/api/zoho/connect/callback': typeof ApiZohoConnectCallbackRoute
  '/practices/ssdi': typeof AuthenticatedPracticesSsdiIndexRoute
  '/practices/ssdi/cases/$caseId': typeof AuthenticatedPracticesSsdiCasesCaseIdRouteWithChildren
  '/practices/ssdi/reports/outcomes': typeof AuthenticatedPracticesSsdiReportsOutcomesRoute
  '/practices/ssdi/reports/pipeline': typeof AuthenticatedPracticesSsdiReportsPipelineRoute
  '/practices/ssdi/reports/referrals': typeof AuthenticatedPracticesSsdiReportsReferralsRoute
  '/practices/ssdi/cases': typeof AuthenticatedPracticesSsdiCasesIndexRoute
  '/practices/ssdi/cases/$caseId/fee-petition': typeof AuthenticatedPracticesSsdiCasesCaseIdFeePetitionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/connect-zoho': typeof AuthenticatedConnectZohoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deadlines': typeof AuthenticatedDeadlinesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/_authenticated/engagements/$engagementId': typeof AuthenticatedEngagementsEngagementIdRoute
  '/_authenticated/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/_authenticated/practices/$practice': typeof AuthenticatedPracticesPracticeRoute
  '/_authenticated/practices/ssdi': typeof AuthenticatedPracticesSsdiRouteWithChildren
  '/_authenticated/settings/changelog': typeof AuthenticatedSettingsChangelogRoute
  '/_authenticated/settings/connections': typeof AuthenticatedSettingsConnectionsRoute
  '/_authenticated/settings/deadline-sweep': typeof AuthenticatedSettingsDeadlineSweepRoute
  '/_authenticated/settings/stage-requirements': typeof AuthenticatedSettingsStageRequirementsRoute
  '/_authenticated/settings/trust-export': typeof AuthenticatedSettingsTrustExportRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/api/public/deadline-sweep': typeof ApiPublicDeadlineSweepRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/engagements/': typeof AuthenticatedEngagementsIndexRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/practices/ssdi/intake': typeof AuthenticatedPracticesSsdiIntakeRoute
  '/api/public/webhooks/zoho-sign': typeof ApiPublicWebhooksZohoSignRoute
  '/api/zoho/connect/callback': typeof ApiZohoConnectCallbackRoute
  '/_authenticated/practices/ssdi/': typeof AuthenticatedPracticesSsdiIndexRoute
  '/_authenticated/practices/ssdi/cases/$caseId': typeof AuthenticatedPracticesSsdiCasesCaseIdRouteWithChildren
  '/_authenticated/practices/ssdi/reports/outcomes': typeof AuthenticatedPracticesSsdiReportsOutcomesRoute
  '/_authenticated/practices/ssdi/reports/pipeline': typeof AuthenticatedPracticesSsdiReportsPipelineRoute
  '/_authenticated/practices/ssdi/reports/referrals': typeof AuthenticatedPracticesSsdiReportsReferralsRoute
  '/_authenticated/practices/ssdi/cases/': typeof AuthenticatedPracticesSsdiCasesIndexRoute
  '/_authenticated/practices/ssdi/cases/$caseId/fee-petition': typeof AuthenticatedPracticesSsdiCasesCaseIdFeePetitionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/connect-zoho'
    | '/dashboard'
    | '/deadlines'
    | '/settings'
    | '/clients/$clientId'
    | '/engagements/$engagementId'
    | '/leads/$leadId'
    | '/practices/$practice'
    | '/practices/ssdi'
    | '/settings/changelog'
    | '/settings/connections'
    | '/settings/deadline-sweep'
    | '/settings/stage-requirements'
    | '/settings/trust-export'
    | '/settings/users'
    | '/api/public/deadline-sweep'
    | '/clients/'
    | '/engagements/'
    | '/leads/'
    | '/settings/'
    | '/practices/ssdi/intake'
    | '/api/public/webhooks/zoho-sign'
    | '/api/zoho/connect/callback'
    | '/practices/ssdi/'
    | '/practices/ssdi/cases/$caseId'
    | '/practices/ssdi/reports/outcomes'
    | '/practices/ssdi/reports/pipeline'
    | '/practices/ssdi/reports/referrals'
    | '/practices/ssdi/cases/'
    | '/practices/ssdi/cases/$caseId/fee-petition'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/connect-zoho'
    | '/dashboard'
    | '/deadlines'
    | '/clients/$clientId'
    | '/engagements/$engagementId'
    | '/leads/$leadId'
    | '/practices/$practice'
    | '/settings/changelog'
    | '/settings/connections'
    | '/settings/deadline-sweep'
    | '/settings/stage-requirements'
    | '/settings/trust-export'
    | '/settings/users'
    | '/api/public/deadline-sweep'
    | '/clients'
    | '/engagements'
    | '/leads'
    | '/settings'
    | '/practices/ssdi/intake'
    | '/api/public/webhooks/zoho-sign'
    | '/api/zoho/connect/callback'
    | '/practices/ssdi'
    | '/practices/ssdi/cases/$caseId'
    | '/practices/ssdi/reports/outcomes'
    | '/practices/ssdi/reports/pipeline'
    | '/practices/ssdi/reports/referrals'
    | '/practices/ssdi/cases'
    | '/practices/ssdi/cases/$caseId/fee-petition'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/connect-zoho'
    | '/_authenticated/dashboard'
    | '/_authenticated/deadlines'
    | '/_authenticated/settings'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/engagements/$engagementId'
    | '/_authenticated/leads/$leadId'
    | '/_authenticated/practices/$practice'
    | '/_authenticated/practices/ssdi'
    | '/_authenticated/settings/changelog'
    | '/_authenticated/settings/connections'
    | '/_authenticated/settings/deadline-sweep'
    | '/_authenticated/settings/stage-requirements'
    | '/_authenticated/settings/trust-export'
    | '/_authenticated/settings/users'
    | '/api/public/deadline-sweep'
    | '/_authenticated/clients/'
    | '/_authenticated/engagements/'
    | '/_authenticated/leads/'
    | '/_authenticated/settings/'
    | '/_authenticated/practices/ssdi/intake'
    | '/api/public/webhooks/zoho-sign'
    | '/api/zoho/connect/callback'
    | '/_authenticated/practices/ssdi/'
    | '/_authenticated/practices/ssdi/cases/$caseId'
    | '/_authenticated/practices/ssdi/reports/outcomes'
    | '/_authenticated/practices/ssdi/reports/pipeline'
    | '/_authenticated/practices/ssdi/reports/referrals'
    | '/_authenticated/practices/ssdi/cases/'
    | '/_authenticated/practices/ssdi/cases/$caseId/fee-petition'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicDeadlineSweepRoute: typeof ApiPublicDeadlineSweepRoute
  ApiPublicWebhooksZohoSignRoute: typeof ApiPublicWebhooksZohoSignRoute
  ApiZohoConnectCallbackRoute: typeof ApiZohoConnectCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deadlines': {
      id: '/_authenticated/deadlines'
      path: '/deadlines'
      fullPath: '/deadlines'
      preLoaderRoute: typeof AuthenticatedDeadlinesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connect-zoho': {
      id: '/_authenticated/connect-zoho'
      path: '/connect-zoho'
      fullPath: '/connect-zoho'
      preLoaderRoute: typeof AuthenticatedConnectZohoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engagements/': {
      id: '/_authenticated/engagements/'
      path: '/engagements'
      fullPath: '/engagements/'
      preLoaderRoute: typeof AuthenticatedEngagementsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/deadline-sweep': {
      id: '/api/public/deadline-sweep'
      path: '/api/public/deadline-sweep'
      fullPath: '/api/public/deadline-sweep'
      preLoaderRoute: typeof ApiPublicDeadlineSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/trust-export': {
      id: '/_authenticated/settings/trust-export'
      path: '/trust-export'
      fullPath: '/settings/trust-export'
      preLoaderRoute: typeof AuthenticatedSettingsTrustExportRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/stage-requirements': {
      id: '/_authenticated/settings/stage-requirements'
      path: '/stage-requirements'
      fullPath: '/settings/stage-requirements'
      preLoaderRoute: typeof AuthenticatedSettingsStageRequirementsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/deadline-sweep': {
      id: '/_authenticated/settings/deadline-sweep'
      path: '/deadline-sweep'
      fullPath: '/settings/deadline-sweep'
      preLoaderRoute: typeof AuthenticatedSettingsDeadlineSweepRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/connections': {
      id: '/_authenticated/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof AuthenticatedSettingsConnectionsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/changelog': {
      id: '/_authenticated/settings/changelog'
      path: '/changelog'
      fullPath: '/settings/changelog'
      preLoaderRoute: typeof AuthenticatedSettingsChangelogRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/practices/ssdi': {
      id: '/_authenticated/practices/ssdi'
      path: '/practices/ssdi'
      fullPath: '/practices/ssdi'
      preLoaderRoute: typeof AuthenticatedPracticesSsdiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practices/$practice': {
      id: '/_authenticated/practices/$practice'
      path: '/practices/$practice'
      fullPath: '/practices/$practice'
      preLoaderRoute: typeof AuthenticatedPracticesPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/$leadId': {
      id: '/_authenticated/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AuthenticatedLeadsLeadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engagements/$engagementId': {
      id: '/_authenticated/engagements/$engagementId'
      path: '/engagements/$engagementId'
      fullPath: '/engagements/$engagementId'
      preLoaderRoute: typeof AuthenticatedEngagementsEngagementIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practices/ssdi/': {
      id: '/_authenticated/practices/ssdi/'
      path: '/'
      fullPath: '/practices/ssdi/'
      preLoaderRoute: typeof AuthenticatedPracticesSsdiIndexRouteImport
      parentRoute: typeof AuthenticatedPracticesSsdiRoute
    }
    '/api/zoho/connect/callback': {
      id: '/api/zoho/connect/callback'
      path: '/api/zoho/connect/callback'
      fullPath: '/api/zoho/connect/callback'
      preLoaderRoute: typeof ApiZohoConnectCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/zoho-sign': {
      id: '/api/public/webhooks/zoho-sign'
      path: '/api/public/webhooks/zoho-sign'
      fullPath: '/api/public/webhooks/zoho-sign'
      preLoaderRoute: typeof ApiPublicWebhooksZohoSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/practices/ssdi/intake': {
      id: '/_authenticated/practices/ssdi/intake'
      path: '/intake'
      fullPath: '/practices/ssdi/intake'
      preLoaderRoute: typeof AuthenticatedPracticesSsdiIntakeRouteImport
      parentRoute: typeof AuthenticatedPracticesSsdiRoute
    }
    '/_authenticated/practices/ssdi/cases/': {
      id: '/_authenticated/practices/ssdi/cases/'
      path: '/cases'
      fullPath: '/practices/ssdi/cases/'
      preLoaderRoute: typeof AuthenticatedPracticesSsdiCasesIndexRouteImport
      parentRoute: typeof AuthenticatedPracticesSsdiRoute
    }
    '/_authenticated/practices/ssdi/reports/referrals': {
      id: '/_authenticated/practices/ssdi/reports/referrals'
      path: '/reports/referrals'
      fullPath: '/practices/ssdi/reports/referrals'
      preLoaderRoute: typeof AuthenticatedPracticesSsdiReportsReferralsRouteImport
      parentRoute: typeof AuthenticatedPracticesSsdiRoute
    }
    '/_authenticated/practices/ssdi/reports/pipeline': {
      id: '/_authenticated/practices/ssdi/reports/pipeline'
      path: '/reports/pipeline'
      fullPath: '/practices/ssdi/reports/pipeline'
      preLoaderRoute: typeof AuthenticatedPracticesSsdiReportsPipelineRouteImport
      parentRoute: typeof AuthenticatedPracticesSsdiRoute
    }
    '/_authenticated/practices/ssdi/reports/outcomes': {
      id: '/_authenticated/practices/ssdi/reports/outcomes'
      path: '/reports/outcomes'
      fullPath: '/practices/ssdi/reports/outcomes'
      preLoaderRoute: typeof AuthenticatedPracticesSsdiReportsOutcomesRouteImport
      parentRoute: typeof AuthenticatedPracticesSsdiRoute
    }
    '/_authenticated/practices/ssdi/cases/$caseId': {
      id: '/_authenticated/practices/ssdi/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/practices/ssdi/cases/$caseId'
      preLoaderRoute: typeof AuthenticatedPracticesSsdiCasesCaseIdRouteImport
      parentRoute: typeof AuthenticatedPracticesSsdiRoute
    }
    '/_authenticated/practices/ssdi/cases/$caseId/fee-petition': {
      id: '/_authenticated/practices/ssdi/cases/$caseId/fee-petition'
      path: '/fee-petition'
      fullPath: '/practices/ssdi/cases/$caseId/fee-petition'
      preLoaderRoute: typeof AuthenticatedPracticesSsdiCasesCaseIdFeePetitionRouteImport
      parentRoute: typeof AuthenticatedPracticesSsdiCasesCaseIdRoute
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsChangelogRoute: typeof AuthenticatedSettingsChangelogRoute
  AuthenticatedSettingsConnectionsRoute: typeof AuthenticatedSettingsConnectionsRoute
  AuthenticatedSettingsDeadlineSweepRoute: typeof AuthenticatedSettingsDeadlineSweepRoute
  AuthenticatedSettingsStageRequirementsRoute: typeof AuthenticatedSettingsStageRequirementsRoute
  AuthenticatedSettingsTrustExportRoute: typeof AuthenticatedSettingsTrustExportRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsChangelogRoute: AuthenticatedSettingsChangelogRoute,
  AuthenticatedSettingsConnectionsRoute: AuthenticatedSettingsConnectionsRoute,
  AuthenticatedSettingsDeadlineSweepRoute:
    AuthenticatedSettingsDeadlineSweepRoute,
  AuthenticatedSettingsStageRequirementsRoute:
    AuthenticatedSettingsStageRequirementsRoute,
  AuthenticatedSettingsTrustExportRoute: AuthenticatedSettingsTrustExportRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedPracticesSsdiCasesCaseIdRouteChildren {
  AuthenticatedPracticesSsdiCasesCaseIdFeePetitionRoute: typeof AuthenticatedPracticesSsdiCasesCaseIdFeePetitionRoute
}

const AuthenticatedPracticesSsdiCasesCaseIdRouteChildren: AuthenticatedPracticesSsdiCasesCaseIdRouteChildren =
  {
    AuthenticatedPracticesSsdiCasesCaseIdFeePetitionRoute:
      AuthenticatedPracticesSsdiCasesCaseIdFeePetitionRoute,
  }

const AuthenticatedPracticesSsdiCasesCaseIdRouteWithChildren =
  AuthenticatedPracticesSsdiCasesCaseIdRoute._addFileChildren(
    AuthenticatedPracticesSsdiCasesCaseIdRouteChildren,
  )

interface AuthenticatedPracticesSsdiRouteChildren {
  AuthenticatedPracticesSsdiIntakeRoute: typeof AuthenticatedPracticesSsdiIntakeRoute
  AuthenticatedPracticesSsdiIndexRoute: typeof AuthenticatedPracticesSsdiIndexRoute
  AuthenticatedPracticesSsdiCasesCaseIdRoute: typeof AuthenticatedPracticesSsdiCasesCaseIdRouteWithChildren
  AuthenticatedPracticesSsdiReportsOutcomesRoute: typeof AuthenticatedPracticesSsdiReportsOutcomesRoute
  AuthenticatedPracticesSsdiReportsPipelineRoute: typeof AuthenticatedPracticesSsdiReportsPipelineRoute
  AuthenticatedPracticesSsdiReportsReferralsRoute: typeof AuthenticatedPracticesSsdiReportsReferralsRoute
  AuthenticatedPracticesSsdiCasesIndexRoute: typeof AuthenticatedPracticesSsdiCasesIndexRoute
}

const AuthenticatedPracticesSsdiRouteChildren: AuthenticatedPracticesSsdiRouteChildren =
  {
    AuthenticatedPracticesSsdiIntakeRoute:
      AuthenticatedPracticesSsdiIntakeRoute,
    AuthenticatedPracticesSsdiIndexRoute: AuthenticatedPracticesSsdiIndexRoute,
    AuthenticatedPracticesSsdiCasesCaseIdRoute:
      AuthenticatedPracticesSsdiCasesCaseIdRouteWithChildren,
    AuthenticatedPracticesSsdiReportsOutcomesRoute:
      AuthenticatedPracticesSsdiReportsOutcomesRoute,
    AuthenticatedPracticesSsdiReportsPipelineRoute:
      AuthenticatedPracticesSsdiReportsPipelineRoute,
    AuthenticatedPracticesSsdiReportsReferralsRoute:
      AuthenticatedPracticesSsdiReportsReferralsRoute,
    AuthenticatedPracticesSsdiCasesIndexRoute:
      AuthenticatedPracticesSsdiCasesIndexRoute,
  }

const AuthenticatedPracticesSsdiRouteWithChildren =
  AuthenticatedPracticesSsdiRoute._addFileChildren(
    AuthenticatedPracticesSsdiRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConnectZohoRoute: typeof AuthenticatedConnectZohoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeadlinesRoute: typeof AuthenticatedDeadlinesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRoute
  AuthenticatedEngagementsEngagementIdRoute: typeof AuthenticatedEngagementsEngagementIdRoute
  AuthenticatedLeadsLeadIdRoute: typeof AuthenticatedLeadsLeadIdRoute
  AuthenticatedPracticesPracticeRoute: typeof AuthenticatedPracticesPracticeRoute
  AuthenticatedPracticesSsdiRoute: typeof AuthenticatedPracticesSsdiRouteWithChildren
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedEngagementsIndexRoute: typeof AuthenticatedEngagementsIndexRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConnectZohoRoute: AuthenticatedConnectZohoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeadlinesRoute: AuthenticatedDeadlinesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedClientsClientIdRoute: AuthenticatedClientsClientIdRoute,
  AuthenticatedEngagementsEngagementIdRoute:
    AuthenticatedEngagementsEngagementIdRoute,
  AuthenticatedLeadsLeadIdRoute: AuthenticatedLeadsLeadIdRoute,
  AuthenticatedPracticesPracticeRoute: AuthenticatedPracticesPracticeRoute,
  AuthenticatedPracticesSsdiRoute: AuthenticatedPracticesSsdiRouteWithChildren,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedEngagementsIndexRoute: AuthenticatedEngagementsIndexRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicDeadlineSweepRoute: ApiPublicDeadlineSweepRoute,
  ApiPublicWebhooksZohoSignRoute: ApiPublicWebhooksZohoSignRoute,
  ApiZohoConnectCallbackRoute: ApiZohoConnectCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
